# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://huos3203.github.io/MyBlog
title: 布衣男儿
subtitle: 不以物喜，不以己悲，善假于物也！
author: 四棵松
simple_search: https://www.google.com/search
description: 从心而行

# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /MyBlog/atom.xml
subscribe_email: 724987481@qq.com
# RSS feeds can list your email address if you like
email:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /MyBlog
permalink: /blog/:year/:month/:day/:title/
source: source
destination: public/MyBlog
plugins: plugins
code_dir: downloads/code
category_dir: blog/categories
tag_dir: tags
markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
pygments: false # default python pygments have been replaced by pygments.rb

paginate: 10          # Posts per page on the blog index  每页展示blog的个数，起到分页效果
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section  左侧最近发表blog的数量

# 在某篇blog中使用<!-- more -->，起到截取保留前半部分的作用，列表页就不会展现该blog全文，就会显示这个read on链接，指向blog全文
# excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_link: "阅读更多 →"

titlecase: true       # Converts page and post titles to titlecase

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
# 右侧边栏的展现，有些要下面的设置配合，比如你没有配置github_user，则这儿也不会展现github.html
# 也可以增加一些自己的页面，比如在/source/_includes/custom/asides/下增加about.html
# 然后在列表中增加custom/asides/about.html即可，这儿前后的顺序，就代表了页面上下的次序 
default_asides: [asides/category_list.html, custom/asides/tags.html, custom/asides/category_cloud.html, custom/asides/tag_cloud.html, asides/recent_posts.html, asides/recent_comments.html, asides/github.html, asides/delicious.html, asides/pinboard.html, asides/googleplus.html,  custom/asides/weibo.html, asides/earth.html]

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.

# <!-- 可以给不同的页面配置不同的侧边栏 -->
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: huos3203
github_repo_count: 3
github_show_profile_link: true
github_skip_forks: true

# Twitter
# twitter_user:	
# twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: huos3203@gmail.com
googleplus_hidden: false

# Pinboard
# pinboard_user:
# pinboard_count: 3

# Delicious
# delicious_user:
# delicious_count: 3

# Disqus Comments
# disqus_short_name:
# disqus_show_comment_count: false

# Google Analytics
#其中 Google Analytics 是Octopress自带的统计工具，使用方式也非常简单，只需要到 Google Analytics 申请一个 app id ，填写到 _config.yml 文件中的 google_analytics_tracking_id 后面即可。

google_analytics_tracking_id: UA-51742113-2

# Facebook Like
# facebook_like: false


##duoshuo comments  
duoshuo_comments: true  
duoshuo_short_name: huo3203

duoshuo_asides_num: 10      # 侧边栏评论显示条目数
duoshuo_asides_avatars: 0   # 侧边栏评论是否显示头像
duoshuo_asides_time: 0      # 侧边栏评论是否显示时间
duoshuo_asides_title: 0     # 侧边栏评论是否显示标题
duoshuo_asides_admin: 0     # 侧边栏评论是否显示作者评论
duoshuo_asides_length: 18   # 侧边栏评论截取的长度
